### ISSUE TITLE
Cannot be installed on Laravel 8

### ISSUE THREAD

**Issue by kconde2** [MrAtiebatie/laravel-repositories#11]
I am getting error below with this version :

`"mratiebatie/laravel-repositories": "^1.0.8",`

![image](https://user-images.githubusercontent.com/43377621/95033016-f7721800-06bc-11eb-8329-c829cdaace19.png)

**Comment by MrAtiebatie** [comment]
I updated the repo and if I'm not mistaken you can now use it with laravel 8. My apologies for the delay.
