### ISSUE TITLE
Change description

### ISSUE THREAD

**Issue by Christophvh** [MrAtiebatie/laravel-repositories#2]
Hi,

Turn repositories into Eloquent repositories in an eye blink.

Should be:

Turn repositories into Eloquent repositories in the blink of an eye.

Reference:
https://dictionary.cambridge.org/dictionary/english/in-the-blink-of-an-eye#targetText=C2%20extremely%20quickly%3A,an%20eye%2C%20he%20was%20gone.

**Comment by MrAtiebatie** [comment]
Thanks
