### ISSUE TITLE
[SUGGESTION] Improvements

### ISSUE THREAD

**Issue by YannickYayo** [MrAtiebatie/laravel-repositories#6]
Hi,

I'm using your package and i feel like we can improve it.

For me, it's not necessary for our Repository class to extends `Illuminate\Database\Eloquent\Model`.
For all model/eloquent builder methods calls we just have to call them on the `protected $model ` property, itself already extending `Illuminate\Database\Eloquent\Model`.

So your `Repository` trait could be :
``` php
/**
 * On method call
 */
 public function __call($method, $arguments)
 {
     if (! method_exists($this, $method)) {
         return $this->model->$method(...$arguments);
     }
 }
```

Then i think the package could provide a `php artisan make:repository TodoRepository` command to create our repository, and maybe add an option to setup the model : `php artisan make:repository --model=App\Todo TodoRepository`.

Finally, it could be good in the `README.md` to provide explanations to create a Facade for our repository, this way we can use it like our models, without DI : 

With DI : 
``` php
public function index(TodoRepository $todoRepository): View
{
    $todos = $todoRepository->all();

    view('todo.view', compact($todos));
}
```

With Facade : 
``` php
public function index(): View
{
    $todos = TodoRepository::all();

    view('todo.view', compact($todos));
}
```

Let me know what you think, i can work on a PR :)

**Comment by MrAtiebatie** [comment]
Hi Yannick, 

Thanks for using the package and your feedback. I think your feedback points are good points to include. If you create a PR I will be happy to accept it. If you need any help just contact me cause I have some spare time the upcoming weeks as well :)

**Comment by YannickYayo** [comment]
Ok nice i'll work on it :D 
I hope stopping extending our repositories from `Illuminate\Database\Eloquent\Model` will not have side effects, maybe you did this extend on purpose ?

**Comment by MrAtiebatie** [comment]
I used your pull request in one of my projects and it still worked so I think that was a little mistake on my side ;-)
